scrape_configs:
  - job_name: 'Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['spring-boot:8080']
        labels:
          application: 'Application'
